version: "3.6"

services:
  mongo:
    image: mongo:6.0.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - etcd_data:/bitnami/etcd
    ports:
      - 2379:2379

  indexer:
    image: quay.io/apibara/cli:0.1
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env
      - /data/src/main.ts
    volumes:
      - ${PWD}/:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: sales-indexer
      AUTH_TOKEN: dna_xxx

volumes:
  etcd_data:
  mongo_data:
