version: "3.6"

services:
  mongo:
    image: mongo:6.0.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - etcd_data:/bitnami/etcd

  indexer_id_owners:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env
      - /data/src/id_owners.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: id-owners
      AUTH_TOKEN: dna_xxx

  indexer_id_user_data:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env
      - /data/src/id_user_data.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: id-user-data
      AUTH_TOKEN: dna_xxx

  indexer_id_verifier_data:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env
      - /data/src/id_verifier_data.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: id-verifier-data
      AUTH_TOKEN: dna_xxx

  indexer_old_domains:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env
      - /data/src/old-domains.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: old-domains
      AUTH_TOKEN: dna_xxx

  indexer_referral_revenues:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env
      - /data/src/referral_revenues.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: referral-revenues
      AUTH_TOKEN: dna_xxx

volumes:
  etcd_data:
  mongo_data:
